import dynamic from 'next/dynamic'
import ToolPanelSkeleton from '@/components/ui/ToolPanelSkeleton'

const load = (importer) =>
  dynamic(importer, { loading: () => <ToolPanelSkeleton />, ssr: false })

export const TOOL_COMPONENTS = {
  'step-solver': load(() => import('@/components/tools/StepByStepSolver')),
  'quadratic-enhanced': load(() => import('@/components/tools/QuadraticSolverEnhanced')),
  'concept-simplifier': load(() => import('@/components/tools/ConceptSimplifier')),
  'mistake-analyzer': load(() => import('@/components/tools/MistakeAnalyzer')),
  'hint-generator': load(() => import('@/components/tools/HintGenerator')),
  'visual-graph': load(() => import('@/components/tools/VisualGraphTool')),
  'fraction-viz': load(() => import('@/components/tools/FractionVisualizer')),
  'number-line': load(() => import('@/components/tools/NumberLine')),
  'timed-practice': load(() => import('@/components/tools/TimedPractice')),
  'practice-gen': load(() => import('@/components/tools/PracticeGenerator')),
  'formula-explorer': load(() => import('@/components/tools/FormulaExplorer')),
  'equation-builder': load(() => import('@/components/tools/EquationBuilder')),
  'geometry-viz': load(() => import('@/components/tools/GeometryVisualizer')),
  'daily-challenge': load(() => import('@/components/tools/DailyChallenge')),
  'advanced-calc': load(() => import('@/components/tools/AdvancedCalculator')),
  percentage: load(() => import('@/components/tools/PercentageCalculator')),
  fraction: load(() => import('@/components/tools/FractionCalculator')),
  ratio: load(() => import('@/components/tools/RatioCalculator')),
  lcmgcd: load(() => import('@/components/tools/LCMGCDCalculator')),
  prime: load(() => import('@/components/tools/PrimeChecker')),
  factorial: load(() => import('@/components/tools/FactorialCalculator')),
  exponent: load(() => import('@/components/tools/ExponentCalculator')),
  area: load(() => import('@/components/tools/AreaCalculator')),
  volume: load(() => import('@/components/tools/VolumeCalculator')),
  root: load(() => import('@/components/tools/RootCalculator')),
  trigonometry: load(() => import('@/components/tools/TrigonometryCalculator')),
  quadratic: load(() => import('@/components/tools/QuadraticSolver')),
  linear: load(() => import('@/components/tools/LinearEquationSolver')),
  graphing: load(() => import('@/components/tools/GraphingCalculator')),
  logarithm: load(() => import('@/components/tools/LogarithmCalculator')),
  sequence: load(() => import('@/components/tools/SequenceCalculator')),
  statistics: load(() => import('@/components/tools/StatisticsCalculator')),
  permutation: load(() => import('@/components/tools/PermutationCombination')),
  probability: load(() => import('@/components/tools/ProbabilityCalculator')),
  derivative: load(() => import('@/components/tools/DerivativeCalculator')),
  integral: load(() => import('@/components/tools/IntegralCalculator')),
  limit: load(() => import('@/components/tools/LimitCalculator')),
  matrix: load(() => import('@/components/tools/MatrixCalculator')),
  vector: load(() => import('@/components/tools/VectorCalculator')),
  complex: load(() => import('@/components/tools/ComplexNumberCalculator')),
}
